### ISSUE TITLE
[Windows] cant pause 

### ISSUE THREAD

**Issue by Rickmazr** [ysdragon/StreamBot#18]
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: SIGSTOP
    at new NodeError (node:internal/errors:399:5)
    at convertToValidSignal (node:internal/util:306:9)
    at ChildProcess.kill (node:internal/child_process:488:5)
    at proto.kill (C:\Users\Administrator\OneDrive\Desktop\botsadmin\StreamBot-main\node_modules\fluent-ffmpeg\lib\processor.js:656:23)
    at Client.<anonymous> (C:\Users\Administrator\OneDrive\Desktop\botsadmin\StreamBot-main\dist\index.js:285:53)
    at Client.emit (node:events:513:28)
    at MessageCreateAction.handle (C:\Users\Administrator\OneDrive\Desktop\botsadmin\StreamBot-main\node_modules\discord.js-selfbot-v13\src\client\actions\MessageCreate.js:30:14)
    at module.exports [as MESSAGE_CREATE] (C:\Users\Administrator\OneDrive\Desktop\botsadmin\StreamBot-main\node_modules\discord.js-selfbot-v13\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Administrator\OneDrive\Desktop\botsadmin\StreamBot-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:366:31)
    at WebSocketShard.onPacket (C:\Users\Administrator\OneDrive\Desktop\botsadmin\StreamBot-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:499:22) {
  code: 'ERR_UNKNOWN_SIGNAL'
}

Node.js v18.16.0

**Comment by ysdragon** [comment]
This issue because you're running it on windows, and `SIGSTOP`  is for linux-only

**Comment by SafwanWilson** [comment]
> This issue because you're running it on windows, and `SIGSTOP` is for linux-only, i will make it compatible with windows soon.

Thank you Waiting For Update

**Comment by ConstructStudios** [comment]
@Rickmazr Whats your discord or best way to contact u

**Comment by ysdragon** [comment]
After some time, I'm not planning to support Windows natively; you can run this bot in WSL2.
