### ISSUE TITLE
need "verify" discord bot?

### ISSUE THREAD

**Issue by Blendi87** [ysdragon/StreamBot#34]
**Do I need a certified discord bot, or why do I get this error code?**

#/home/bots/StreamBot/node_modules/.pnpm/discord.js-selfbot-v13@3.1.4/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:244
        throw new Error(WSCodes[error.code]);
              ^
Error [INVALID_INTENTS]: [Bot Token] Invalid intent provided for WebSocket intents.
    at WebSocketManager.createShards (/home/bots/StreamBot/node_modules/.pnpm/discord.js-selfbot-v13@3.1.4/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:244:15)
    at async Client.login (/home/bots/StreamBot/node_modules/.pnpm/discord.js-selfbot-v13@3.1.4/node_modules/discord.js-selfbot-v13/src/client/Client.js:266:7) {
  [Symbol(code)]: 'INVALID_INTENTS'
}
Node.js v20.15.0
 ELIFECYCLE  Command failed with exit code 1.

![Screenshot_1](https://github.com/ysdragon/StreamBot/assets/174760305/6d68a0f2-5502-4940-99fd-594ed4fccb40)

**I am somewhat at a loss

does anyone have a tip? or better still the solution? :)

OT: i like your work :)**

**Comment by ysdragon** [comment]
Please read the README.md carefully!
