### ISSUE TITLE
Add ability to set cookies for ytdl-core

### ISSUE THREAD

**Issue by Algerization** [ysdragon/StreamBot#63]
Error occurred while getting video URL: 159 |  */
160 | exports.playError = player_response => {
161 |   const playability = player_response && player_response.playabilityStatus;
162 |   if (!playability) return null;
163 |   if (['ERROR', 'LOGIN_REQUIRED'].includes(playability.status)) {
164 |     return new UnrecoverableError(playability.reason || (playability.messages && playability.messages[0]));
                            ^
error: Sign in to confirm you’re not a bot
      at new UnrecoverableError (1:23)
      at C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@distube\ytdl-core\lib\utils.js:164:12
      at C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@distube\ytdl-core\lib\info.js:46:25

**Comment by ysdragon** [comment]
This is because your IP subnet is banned by YouTube.
But, i will look for a solution to set cookies for `ytdl-core`.

**Comment by Algerization** [comment]
> This is because your IP subnet is banned by YouTube. But, i will look for a solution to set cookies for `ytdl-core`.

Banned for what xd? I didn't know that actually

**Comment by Tomcu** [comment]
Would setting these cookies allow me to take advantage of YouTube Premium? Or is that another matter entirely?

**Comment by ysdragon** [comment]
@Tomcu No, this will prevent YouTube from banning your IP or bypassing the `Sign in to confirm you’re not a bot`.

**Comment by Tomcu** [comment]
Is streaming with YT premium possible at all?

**Comment by ysdragon** [comment]
Yes, once I implement a way to use OAuth2 with ytdl-core, (of course, you would need a YouTube Premium subscription).

**Comment by Marco5dev** [comment]
![Image](https://github.com/user-attachments/assets/f5e6de31-57a2-4e37-a4ef-71324fcede4a)
The developer is rude

**Comment by Jakilator** [comment]
i believe this is fixed with Cloudflare warp

**Comment by ysdragon** [comment]
> i believe this is fixed with Cloudflare warp

I will implement an option that uses youtube cookies to avoid this error.

**Comment by awakcon1234** [comment]
Pumping this issue up! It would be nice to be able to pass a `cookie.json` file from EditThisCookie directly into `ytdlp`.
