### ISSUE TITLE
Can't be played, Source video or Local Folder

### ISSUE THREAD

**Issue by Algerization** [ysdragon/StreamBot#64]
Started playing video
Playing ( 375456286_267127142851399_4003698449306018315_n )...
18 |         }
19 |         else {
20 |             this.socketPath = './' + (++counter) + '.sock';
21 |             this.url = 'unix:' + this.socketPath;
22 |         }
23 |         try {
     ^
error: Failed to listen at \\.\pipe\node-webrtc.1.sock
 errno: 2
  code: "ENOENT"

      at listen (native:1:1)
      at node:net:688:16
      at node:net:32:30
      at listen (node:net:635:9)
      at new UnixStream (C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@dank074\fluent-ffmpeg-multistream-ts\dist\index.js:23:20)
      at StreamOutput (C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@dank074\fluent-ffmpeg-multistream-ts\dist\index.js:40:16)
      at C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@dank074\discord-video-stream\dist\media\streamLivestreamVideo.js:87:75
      at new Promise (1:11)
      at streamLivestreamVideo (C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@dank074\discord-video-stream\dist\media\streamLivestreamVideo.js:16:16)
      at C:\Users\Rayan\Desktop\StreamBot-main\dist\index.js:378:62
18 |         }
19 |         else {
20 |             this.socketPath = './' + (++counter) + '.sock';
21 |             this.url = 'unix:' + this.socketPath;
22 |         }
23 |         try {
     ^
error: Failed to listen at \\.\pipe\node-webrtc.2.sock
 errno: 2
  code: "ENOENT"

      at listen (native:1:1)
      at node:net:688:16
      at node:net:32:30
      at listen (node:net:635:9)
      at new UnixStream (C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@dank074\fluent-ffmpeg-multistream-ts\dist\index.js:23:20)
      at StreamOutput (C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@dank074\fluent-ffmpeg-multistream-ts\dist\index.js:40:16)
      at C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@dank074\discord-video-stream\dist\media\streamLivestreamVideo.js:110:64
      at new Promise (1:11)
      at streamLivestreamVideo (C:\Users\Rayan\Desktop\StreamBot-main\node_modules\@dank074\discord-video-stream\dist\media\streamLivestreamVideo.js:16:16)
      at C:\Users\Rayan\Desktop\StreamBot-main\dist\index.js:378:62

Bun v1.1.26 (Windows x64 baseline)
error: script "start" exited with code 1

**Comment by ysdragon** [comment]
Hi @Algerization, 
Do NOT use the bot under Windows, it's not supported, run it under WSL2 on windows at least!

**Comment by Algerization** [comment]
> Hi @Algerization, Do NOT use the bot under Windows, it's not supported, run it under WSL2 on windows at least!

I have no Experience running bots on other Platforms. Also, YOU should mention this in the Description of the bot so others can Know that without asking.

THANKS FOR HELPING AND FOR YOUR GREAT WORK!

**Comment by ysdragon** [comment]
> YOU should mention this in the Description of the bot so others can Know that without asking.

Thanks for your suggestion.

**Comment by Algerization** [comment]
> > YOU should mention this in the Description of the bot so others can Know that without asking.
> 
> Thanks for your suggestion.

Running the Bot on Ubuntu is Supported?

**Comment by ysdragon** [comment]
Yes, of course, any Linux distro is supported

**Comment by Algerization** [comment]
> Yes, of course, any Linux distro is supported

Using WSL:
![image](https://github.com/user-attachments/assets/495e7cb4-cf90-4b9d-a216-01effe28b469)

**Comment by ysdragon** [comment]
Weird, I didn't encounter this error before; just Google it!
